Sumatywny/website/auth.py

from flask import Blueprint, render_template, request, flash, redirect, url_for,send_file,make_response,current_app as app
from .models import User,ALLOWED_EXTENSIONS
from flask_login import login_user, login_required, logout_user, current_user
import hashlib, requests
from werkzeug.utils import secure_filename
from .views import send_confirmation_email
from io import BytesIO
from . import db


auth = Blueprint('auth', __name__)

def hash_password(password):
    hash_object = hashlib.sha256()
    hash_object.update(password.encode())
    hashed_password = hash_object.hexdigest()
    return hashed_password

def verify_password(hashed_password, user_password):
    hash_object = hashlib.sha256()
    hash_object.update(user_password.encode())
    user_hashed_password = hash_object.hexdigest()
    return hashed_password == user_hashed_password


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if user.status != "rejected":
                if user.status == "accepted":
                    if verify_password(user.password, password):
                        flash('Zalogowano!', category='success')
                        login_user(user, remember=True)
                        return redirect(url_for('views.home'))
                    else:
                        flash('Błędne hasło spróbuj ponownie.', category='error')
                else:
                    flash('Twoje konto nie zostało jeszcze zatwierdzone.', category='error')
            else:
                flash('Twoje konto zostało odrzucone.', category='error')
        else:
            flash('Email jest błędny.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def choose_signup():
    return render_template("sign_up_type.html", user=current_user)


@auth.route('/sign-up/user', methods=['GET', 'POST'])
def sign_up_user():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        name = request.form.get('name')
        surname = request.form.get('surname')
        address = request.form.get('address')
        pesel = request.form.get('pesel')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        front_document_image = request.files.get('front_document_image')
        back_document_image = request.files.get('back_document_image')

        user = User.query.filter_by(email=email).first()
        check_pesel = User.query.filter_by(uid=pesel).first()
        check_username = User.query.filter_by(username=username).first()

        if user:
            flash('Konto już istnieje.', category='error')
        elif len(email) < 3:
            flash('Email musi mieć więcej niż 3 znaki.', category='error')
        elif len(username) < 3:
            flash('Nazwa użytkownika musi mieć więcej niż 3 znaki.', category='error')
        elif check_username:
            flash('Nazwa użytkownika już istnieje.', category='error')
        elif len(name) < 2:
            flash('Imię musi być dłuższe niż 2 znaki.', category='error')
        elif len(surname) < 2:
            flash('Nazwisko musi być dłuższe niż 2 znaki.', category='error')
        elif len(address) < 2:
            flash('Adres musi być dłuższy niż 2 znaki.', category='error')
        elif len(pesel) != 11:
            flash('Pesel musi posiadać równo 11 liczb.', category='error')
        elif check_pesel:
            flash('Pesel już istnieje.', category='error')
        elif password1 != password2:
            flash('Hasła nie są takie same.', category='error')
        elif len(password1) < 7:
            flash('Hasło musi się składać z 7 znaków.', category='error')
        elif front_document_image and allowed_file(front_document_image.filename) and back_document_image:
            front_document_image_data = front_document_image.read()
            back_document_image_data = back_document_image.read()
            new_user = User(email=email, username=username, name=name, surname=surname, address=address,
                                uid=pesel, password=hash_password(password1), front_document_image=front_document_image_data,back_document_image=back_document_image_data)
            db.session.add(new_user)
            db.session.commit()
            send_confirmation_email(new_user)
            flash('Konto musi przejść jeszcze etap zatwierdzenia!', category='success')
            return redirect(url_for('views.home'))
        else:
            flash('Nieprawidłowy plik obrazu.', category='error')
    
    return render_template("sign_up_user.html", user=current_user)

@auth.route('/sign-up/org', methods=['GET', 'POST'])
def sign_up_org():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        address = request.form.get('address')
        nip = request.form.get('nip')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        check_nip = User.query.filter_by(uid=nip).first()
        if user:
            flash('Konto już istnieje.', category='error')
        elif len(email) < 3:
            flash('Email musi mieć więcej niż 3 znaki.', category='error')
        elif len(name) < 2:
            flash('Imię musi być dłuższe niż 2 znaki.', category='error')
        elif len(address) < 2:
            flash('Adres musi być dłuższy niż 2 znaki.', category='error')
        elif len(nip) != 10:
            flash('NIP musi posiadać równo 10 liczb.', category='error')
        elif not validate_nip(nip):
            flash('NIP jest nieprawidłowy.', category='error')
        elif check_nip:
            flash('NIP już istnieje.', category='error')
        elif password1 != password2:
            flash('Hasła nie są takie same.', category='error')
        elif len(password1) < 7:
            flash('Hasło musi się składać z 7 znaków.', category='error')
        else:
            new_user = User(email=email, name=name, address=address, uid=nip, role='organisation', password=hash_password(password1))
            db.session.add(new_user)
            db.session.commit()
            send_confirmation_email(new_user)
            flash('Konto musi przejść jeszcze etap zatwierdzenia!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up_org.html", user=current_user)
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@auth.route('/front-document-image/<int:user_id>')
def get_front_document_image(user_id):
    user = User.query.get_or_404(user_id)
    if user.front_document_image:
        return send_file(BytesIO(user.front_document_image), mimetype='image/jpeg')
    else:
        return make_response("No image found", 404)
    
@auth.route('/back-document-image/<int:user_id>')
def get_back_document_image(user_id):
    user = User.query.get_or_404(user_id)
    if user.back_document_image:
        return send_file(BytesIO(user.back_document_image), mimetype='image/jpeg')
    else:
        return make_response("No image found", 404)
    


def validate_nip(nip):
    api_key = app.config['NIP24_API_KEY']
    url = f'https://www.nip24.pl/api/nip/{nip}?key={api_key}'
    
    try:
        response = requests.get(url, verify=False)  # Remember to remove verify=False for production use
        if response.status_code == 200:
            data = response.json()
            return data.get('valid', False)
    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    return False

Sumatywny/website/templates/admin_reports.html
{% extends "base.html" %}
{% block title %}Weryfikacja zgłoszeń{% endblock %}
{% block content %}
<style>
.banner {
    width: 100%; 
    background-image: url('{{ url_for('static', filename='naruszenia.png') }}'); 
    background-size: cover; 
    background-position: center; 
    height: 400px; 
    border-radius: 15px; 
}
   #container {
    background-color: rgb(250,250,250,1);
    color: #000000; 
    text-align: center;
    padding: 20px;
    border-radius: 15px;
    width: 100%;
    margin: 1% auto; 
  }
  .container_create_survey, .container_create_survey2 {
    position: relative;
    background-color:#b4dfe5;
    color: #000000; 
    justify-content: center;
    align-items: center;
    border-radius: 15px;
    padding: 30px;
    margin-top: 20px;
  }
  .container1, .container2, .container3 {
    background-color: rgb(180,223,229,0.3);
    border-radius: 15px;
    {#border: 2px solid white; #}
    overflow: hidden; 
    font-family: Arial, sans-serif; 
  }

  .btn-group {
    display: flex;
    justify-content: center;
    margin-top: 15px;
  }
  .btn-group form {
    margin: 0 5px;
  }
  .list-group-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }
</style>
    <div class="banner"></div>
<div id="container">
  <h1 class="text-center">Weryfikacja naruszeń środowiskowych</h1>
  <div class="container_create_survey">
    <ul class="list-group list-group-flush">
    {% if pending_reports%}
      {% for report in pending_reports %}
        <li class="list-group-item container3">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ report.name }}</h5>
            <small><strong>Data:</strong>{{ report.date }}</small>
          </div>
          <p class="mb-1"><strong>Opis wydarzeń:</strong>{{ report.data }}</p>
          <p class="mb-1"><strong>Miejsce wydarzeń:</strong>{{ report.place }}</p>
          <div class="btn-group" role="group">
            <form method="POST" action="{{ url_for('views.update_report_status', report_id=report.id, action='accept') }}">
              <button type="submit" class="btn btn-success">Zaakceptuj</button>
            </form>
            <form method="POST" action="{{ url_for('views.update_report_status', report_id=report.id, action='reject') }}">
              <button type="submit" class="btn btn-danger">Odrzuć</button>
            </form>
          </div>
        </li>
      {% endfor %}
    {% else %}
        <p>Brak pozycji do wyświetlenia.</p>
    {% endif %}
    </ul>
  </div>
</div>

{% endblock %}

Sumatywny/website/templates/admin_survey_responses.html
{% extends "base.html" %}
{% block title %}All Survey Responses{% endblock %}
{% block content %}
<style>
    .banner {
        width: 100%;
        background-image: url('{{ url_for('static', filename='ankiety.png') }}');
        background-size: cover;
        background-position: center;
        height: 400px;
        border-radius: 15px;
    }
    #container {
        background-color: rgb(250,250,250,1);
        color: #000000;
        text-align: center;
        padding: 20px;
        border-radius: 15px;
        width: 100%;
        margin: 1% auto;
        max-height: calc(100vh - 480px);
        overflow-y: auto;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    th, td {
        padding: 10px;
        border: 1px solid #ddd;
    }
    th {
        background-color: #b4dfe5;
    }
</style>
<div class="banner"></div>
<div id="container">
    <h1>All Survey Responses</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Survey ID</th>
                <th>Response ID</th>
                <th>Responses</th>
            </tr>
        </thead>
        <tbody>
            {% for response in responses %}
            <tr>
                <td>{{ response.survey_id }}</td>
                <td>{{ response.id }}</td>
                <td>{{ response.answers }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

Sumatywny/website/templates/admin_users.html
{% extends "base.html" %}
{% block title %}Weryfikacja użytkowników{% endblock %}
{% block content %}
<style>
    .banner {
        width: 100%;
        background-image: url('{{ url_for('static', filename='znajomi.png') }}');
        background-size: cover;
        background-position: center;
        height: 400px;
        border-radius: 15px;
    }

    #container {
        background-color: rgb(250, 250, 250, 1);
        color: #000000;
        text-align: center;
        padding: 20px;
        border-radius: 15px;
        width: 100%;
        margin: 1% auto;
    }

    .container_create_survey,
    .container_create_survey2,
    .container_accepted,
    .container_accepted_org {
        background-color: #b4dfe5;
        color: #000000;
        justify-content: center;
        align-items: center;
        border-radius: 15px;
        padding: 15px;
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .user-card {
        background-color: #e3f2fd;
        border-radius: 15px;
        overflow: hidden;
        font-family: Arial, sans-serif;
        margin: 10px;
        padding: 20px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        text-align: left;
    }

    .user-card strong {
        display: inline-block;
        width: 150px;
    }

    .btn-group {
        display: flex;
        justify-content: center;
        margin-top: 15px;
    }

    .btn-group form {
        margin: 0 5px;
    }

    .dashed-line {
        border-top: 2px dashed #000000;
        margin: 20px 0;
    }

    h3 {
        margin-bottom: 20px;
    }
    .btn-t {
        background-color: #328685;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }
</style>
<div class="banner"></div>
<div id="container">
    <h1 class="text-center">Autoryzacja dostępu</h1>
    <div class="dashed-line"></div>
    <h3 class="mb-0">Weryfikacja organizacji</h3>
    <div class="container_create_survey">
        {% if pending_users|selectattr('role', 'equalto', 'organisation')|list %}
        {% for user in pending_users %}
        {% if user.role == 'organisation' %}
        <div class="user-card">
            <strong>Nazwa:</strong> {{ user.name }}<br>
            <strong>Adres:</strong> {{ user.address }}<br>
            <strong>Email:</strong> {{ user.email }}<br>
            <strong>NIP:</strong> {{ user.uid }}<br>
            {% if user.document_image %}
            <a href="{{ url_for('auth.get_document_image', user_id=user.id) }}" data-lightbox="image-{{ user.id }}" data-title="{{ user.name }}">
                <button class="btn-t">Dokument</button>
            </a>
            {% endif %}
            <div class="btn-group mt-2" role="group">
                <form method="POST" action="{{ url_for('views.update_user_status', user_id=user.id, action='accept') }}">
                    <button type="submit" class="btn btn-success">Zatwierdź</button>
                </form>
                <form method="POST" action="{{ url_for('views.update_user_status', user_id=user.id, action='reject') }}">
                    <button type="submit" class="btn btn-danger">Odrzuć</button>
                </form>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <p>Brak pozycji do wyświetlenia.</p>
        {% endif %}
    </div>
    <h3 class="mb-0">Weryfikacja użytkowników</h3>
    <div class="container_create_survey2">
        {% if pending_users|selectattr('role', 'ne', 'organisation')|list %}
        {% for user in pending_users %}
        {% if user.role != 'organisation' %}
        <div class="user-card">
            <strong>Imię:</strong> {{ user.name }}<br>
            <strong>Nazwisko:</strong> {{ user.surname }}<br>
            <strong>Nazwa użytkownika:</strong> {{ user.username }}<br>
            <strong>Adres:</strong> {{ user.address }}<br>
            <strong>Email:</strong> {{ user.email }}<br>
            <strong>Pesel:</strong> {{ user.uid }}<br>
            {% if user.front_document_image %}
            <a href="{{ url_for('auth.get_front_document_image', user_id=user.id) }}" data-lightbox="image-{{ user.id }}" data-title="{{ user.name }} {{ user.surname }}">
                <button class="btn-t">Przód dokumentu</button>
            </a>
            {% endif %}
            {% if user.back_document_image %}
            <a href="{{ url_for('auth.get_back_document_image', user_id=user.id) }}" data-lightbox="image-{{ user.id }}" data-title="{{ user.name }} {{ user.surname }}">
                <button class="btn-t">Tył dokumentu</button>
            </a>
            {% endif %}
            <div class="btn-group mt-2" role="group">
                <form method="POST" action="{{ url_for('views.update_user_status', user_id=user.id, action='accept') }}">
                    <button type="submit" class="btn btn-success">Zatwierdź</button>
                </form>
                <form method="POST" action="{{ url_for('views.update_user_status', user_id=user.id, action='reject') }}">
                    <button type="submit" class="btn btn-danger">Odrzuć</button>
                </form>
            </div>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <p>Brak pozycji do wyświetlenia.</p>
        {% endif %}
    </div>

    <h3 class="mb-0">Zaakceptowane organizacje</h3>
    <div class="container_accepted_org">
        {% if accepted_users|selectattr('role', 'equalto', 'organisation')|list %}
        {% for user in accepted_users %}
        {% if user.role == 'organisation' %}
        <div class="user-card">
            <strong>Nazwa:</strong> {{ user.name }}<br>
            <strong>Adres:</strong> {{ user.address }}<br>
            <strong>Email:</strong> {{ user.email }}<br>
            <strong>NIP:</strong> {{ user.uid }}<br>
            <div class="btn-group mt-2" role="group">
                {% if user.id != current_user.id %}
                <form method="POST" action="{{ url_for('views.delete_user', user_id=user.id) }}">
                    <button type="submit" class="btn btn-danger">Usuń</button>
                </form>
                {% else %}
                <button class="btn btn-secondary" disabled>Nie można usunąć siebie</button>
                {% endif %}
            </div>
        </div>
        {% endif %}
        {% endfor %}
    {% else %}
        <p>Brak pozycji do wyświetlenia.</p>
        {% endif %}
    </div>

    <h3 class="mb-0">Zaakceptowani użytkownicy</h3>
    <div class="container_accepted">
        {% if accepted_users|selectattr('role', 'ne', 'organisation')|list %}
        {% for user in accepted_users %}
        {% if user.role != 'organisation' %}
        <div class="user-card">
            <strong>Imię:</strong> {{ user.name }}<br>
            <strong>Nazwisko:</strong> {{ user.surname }}<br>
            <strong>Nazwa użytkownika:</strong> {{ user.username }}<br>
            <strong>Adres:</strong> {{ user.address }}<br>
            <strong>Email:</strong> {{ user.email }}<br>
            <strong>Pesel:</strong> {{ user.uid }}<br>
            <div class="btn-group mt-2" role="group">
                {% if user.id != current_user.id %}
                <form method="POST" action="{{ url_for('views.delete_user', user_id=user.id) }}">
                    <button type="submit" class="btn btn-danger">Usuń</button>
                </form>
                {% else %}
                <button class="btn btn-secondary" disabled>Konta admina</button>
                {% endif %}
            </div>
        </div>
        {% endif %}
        {% endfor %}
    {% else %}
        <p>Brak pozycji do wyświetlenia.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

Sumatywny/website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="static/logo.png">
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        body {
            background-image: url('{{ url_for('static', filename='tlo.png') }}'); 
            background-size: cover; 
            background-repeat: no-repeat; 
            background-attachment: fixed; 
            background-position: center; 
            color: #000000; 
            display: flex;
            flex-direction: column;
        }
        .navbar {
            background-color: #2c3e50 !important; 
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .navbar-brand, .navbar-nav .nav-link {
            color: #fff !important; 
            margin-right: 20px;
        }
        .navbar-brand:hover, .navbar-nav .nav-link:hover {
            color: #dcdde1 !important; 
        }
        .navbar-toggler {
            border-color: #fff !important; 
        }
        .navbar-toggler-icon {
            background-image: url('static/menu.jpg'); 
            background-size: cover; 
        }
        .container {
            background-color: rgba(236, 240, 241, 0); 
            border-radius: 5px; 
            max-width: 100%; 
            margin: 20px auto;
            padding: 0 15px; 
            flex: 1;
        }
        .alert {
            margin-bottom: 20px;
        }
        .footer {
            background-color: #2c3e50;
            color: #ffffff;
            text-align: center;
            padding: 10px 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" id="home" href="/">
            <img src="{{ url_for('static', filename='logo.png') }}" alt="E-Gmina" style="height: 40px;">
        </a> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    {% if current_user.role == 'user'%}
                        <a class="nav-item nav-link" id="platnosc-button" href='/payments'>Płatność</a>
                        <a class="nav-item nav-link" id="wymiana-button" href='/exchange'>Wymiana punktów</a>
                        <a class="nav-item nav-link" id="odpady-button" href='/segregate'>Segregacja</a>
                        <a class="nav-item nav-link" id="report-button" href='/report'>Naruszenia środowiskowe</a>
                        <a class="nav-item nav-link" id="ankiety-button" href='/surveys'>Ankiety</a>
                        <a class="nav-item nav-link" id="friends-button" href="/invite-friends">Znajomi</a>
                    {% endif %}
                    {% if current_user.role == 'admin' %}
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="verificationDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Weryfikacja
                            </a>
                            <div class="dropdown-menu" aria-labelledby="verificationDropdown">
                                <a class="dropdown-item" id="admin_events" href="/admin-events">Weryfikuj wydarzenia</a>
                                <a class="dropdown-item" id="admin_users" href="/admin-users">Weryfikuj konta</a>
                                <a class="dropdown-item" id="admin_reports" href="/admin-reports">Weryfikuj zgłoszenia</a>
                                <a class="dropdown-item" id="approve-surveys" href="/approve-surveys">Weryfikuj ankiety</a>
                            </div>
                        </div>
                        <a class="nav-item nav-link" id="admin_payment" href="/admin-payments">Wprowadź płatności</a>
                        <a class="nav-item nav-link" id="wymiana-button" href='/exchange'>System lojalnościowy </a>
                        <a class="nav-item nav-link" id="events" href="/events">Dodaj wydarzenia</a>
                        <a class="nav-item nav-link" id="maps" href="/maps">Ważne miejsca</a>
                        <a class="nav-item nav-link" id="admin_users" href="/create-survey">Ankiety</a>
                        <a class="nav-link nav-link" id="survey-results" href="/survey_results">Wyniki ankiet</a>
                    {% endif %}
                    {% if current_user.role == 'organisation' %}
                        <a class="nav-item nav-link" id="events" href="/events">Dodaj wydarzenia</a>
                        <a class="nav-item nav-link" id="surveys" href="/create-survey">Ankiety</a>
                        <a class="nav-link nav-link" href="/survey_results">Odpowiedzi na ankiety</a>
                    {% endif %}
                {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Zaloguj</a>
                    <a class="nav-item nav-link" id="signUp" href="/sign-up">Zarejestruj</a>
                {% endif %}
            </div>
            <div class="navbar-nav ml-auto"> 
                {% if current_user.is_authenticated %}
                    {% if current_user.role != 'admin' %}
                        <a class="nav-item nav-link" id="user_info" href="/user_info">Konto</a>
                    {% endif %}
                    <a class="nav-item nav-link" id="logout" href="/logout">Wyloguj</a> 
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <div class="footer">
        <p>Kontakt: <a href="mailto:egminakonstantynow@gmail.com" style="color: #ffffff;">egminakonstantynow@gmail.com</a></p>
        <p>Gmina Konstantynów Łódzki, Zgierska 2, 95-050 Konstantynów Łódzki</p>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7W3UibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block javascript %}
    <script type="text/javascript">
        function deleteEvent(eventId) {
            fetch("/delete-event", {
                method: "POST",
                body: JSON.stringify({ eventId: eventId }),
            }).then((_res) => {
                window.location.href = "/events";
            });
        }
    </script>
    <script>
    document.addEventListener("DOMContentLoaded", function() {
        var dropdownItems = document.querySelectorAll(".dropdown-item");
        dropdownItems.forEach(function(item) {
            item.addEventListener("mouseenter", function() {
                this.style.backgroundColor = "#328685";
                this.style.color = "#fff";
            });
            item.addEventListener("mouseleave", function() {
                this.style.backgroundColor = "";
                this.style.color = "";
            });
        });
    });
    </script>
    {% endblock %}
</body>
</html>

Sumatywny/website/templates/login_type.html
{% extends "base.html" %}
{% block title %}Calendar{% endblock %}
{% block content %}
    <div style="text-align: center;">
        <div style="display: inline-block;">
            <img src="{{ url_for('static', filename='użytkownik.png') }}"  width="300" height="200">
            <img src="{{ url_for('static', filename='mcdonalds.png') }}"  width="300" height="200">
            <img src="{{ url_for('static', filename='papież.jpg') }}"  width="300" height="200">
        </div>
        <div>
            <button onclick="ChooseType(1)">Użytkownik</button>
            <button onclick="ChooseType(2)">Organizacja</button>
            <button onclick="ChooseType(3)">Admin</button>
        </div>
    </div>
    <script>
        function ChooseType(Number) {
            switch(Number) {
                case 1:
                    window.location.href = "{{ url_for('auth.login') }}";
                    break;
            }
        }
    </script>
{% endblock %}

Sumatywny/website/templates/organization_survey_responses.html
{% extends "base.html" %}
{% block title %}Survey Responses{% endblock %}
{% block content %}
<h1>Responses for Survey: {{ survey.title }}</h1>
<table class="table">
    <thead>
        <tr>
            <th>Response ID</th>
            <th>Responses</th>
        </tr>
    </thead>
    <tbody>
        {% for response in responses %}
        <tr>
            <td>{{ response.id }}</td>
            <td>{{ response.answers }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}